[project]
name = "delta-debugging"
version = "0.2.0"
dependencies = [
    "kaitaistruct>=0.11",
    "tabulate>=0.9.0",
    "tqdm>=4.67.1",
    "tree-sitter>=0.25.1",
    "tree-sitter-language-pack>=0.9.0",
]
requires-python = ">=3.12"
authors = [
    { name = "Feiyang Chen", email = "fche0060@uni.sydney.edu.au" }
]
description = "A delta debugging framework."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["delta debugging"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python"
]

[project.urls]
Homepage = "https://github.com/FreeFlyingSheep/delta-debugging/"
Documentation = "https://freeflyingsheep.github.io/delta-debugging/"
Repository = "https://github.com/FreeFlyingSheep/delta-debugging.git"
Changelog = "https://github.com/FreeFlyingSheep/delta-debugging/blob/master/CHANGELOG.md"

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pdoc>=15.0.4",
    "pytest>=8.4.1",
    "ruff>=0.13.1",
]

[tool.ruff]
# Exclude auto-generated files.
exclude = [
    "src/delta_debugging/parsers/kaitai_struct_compiled"
]

[tool.ruff.lint]
# Enable Google convention `pydocstyle` rules.
select = ["D", "E", "F", "W", "PL"]
# Ignore specific `pydocstyle` rules.
ignore = ["D203", "D213", "E501", "PLR0913"]

[tool.ruff.lint.per-file-ignores]
# Ignore `D` rules everywhere except for the `src/` directory.
"!src/**.py" = ["D", "PL"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 200
