name: Main Branch Update

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Lint code
        run: uv run ruff check .

      - name: Format code
        run: uv run ruff format --check .

      - name: Run tests
        run: uv run pytest -s -v

      - name: Build documentation
        run: uv run pdoc -o docs -d google delta_debugging

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
